# Generated by Django 4.0.2 on 2022-02-27 17:43

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("core", "0001_add_standard_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "menu_item",
                                wagtail.core.blocks.PageChooserBlock(
                                    wagtail.core.models.Page
                                ),
                            )
                        ],
                        blank=True,
                        help_text="Add menu items to the navigation menu",
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
