# Generated by Django 4.0.2 on 2022-02-26 22:38

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Heading text", required=True
                                    ),
                                ),
                                (
                                    "heading_level",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("h1", "Heading 1"),
                                            ("h2", "Heading 2"),
                                            ("h3", "Heading 3"),
                                            ("h4", "Heading 4"),
                                            ("h5", "Heading 5"),
                                            ("h6", "Heading 6"),
                                        ],
                                        help_text="Heading level",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text",
                        wagtail.core.blocks.RichTextBlock(
                            features=["bold", "italic", "link"], icon="doc-full"
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
